2023-07-18 13:07:16.302707: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-18 13:07:22.086407: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-07-18 13:07:22.086449: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
Traceback (most recent call last):
  File "/home/vishnupk/geocarb/methane_hotspot_detection/base.py", line 509, in <module>
    execute_exp(args, multi_gpus=n_physical_devices)
  File "/home/vishnupk/geocarb/methane_hotspot_detection/base.py", line 338, in execute_exp
    model = create_unet_network(
  File "/home/vishnupk/geocarb/methane_hotspot_detection/unet/model.py", line 60, in create_unet_network
    x = Concatenate()([x_down[i],x])
  File "/home/fagg/miniconda3/envs/tf/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/fagg/miniconda3/envs/tf/lib/python3.10/site-packages/keras/layers/merging/concatenate.py", line 131, in build
    raise ValueError(err_msg)
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concatenation axis. Received: input_shape=[(None, 1, 32, 120), (None, 2, 32, 120)]
